# Generated by Django 3.0.3 on 2021-02-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Nombre'),
        ),
    ]
