# Generated by Django 3.0.3 on 2021-02-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0002_auto_20210224_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Nombre')),
                ('pie', models.TextField(max_length=1500, verbose_name='Pie de página')),
                ('image', models.ImageField(default='null', upload_to='figuras', verbose_name='Figura')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='componente',
            name='public',
        ),
        migrations.AddField(
            model_name='componente',
            name='imagen',
            field=models.ManyToManyField(to='cap2.Imagen', verbose_name='Agregar imagen'),
        ),
    ]
