# Generated by Django 3.0.3 on 2021-02-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0004_componente_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='shirt_size',
        ),
    ]
