# Generated by Django 3.0.3 on 2021-02-25 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0005_remove_componente_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='etapa',
        ),
        migrations.AddField(
            model_name='componente',
            name='etapa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa'),
        ),
        migrations.RemoveField(
            model_name='componente',
            name='fase',
        ),
        migrations.AddField(
            model_name='componente',
            name='fase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase'),
        ),
    ]
