# Generated by Django 3.0.3 on 2021-02-25 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0006_auto_20210225_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imagen',
            name='componente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Componente'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='etapa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='fase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='title',
            field=models.CharField(max_length=350, verbose_name='Nombre'),
        ),
    ]
