# Generated by Django 3.0.3 on 2021-03-02 05:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0007_auto_20210225_0222'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagen',
            managers=[
                ('referencia', django.db.models.manager.Manager()),
            ],
        ),
    ]
