# Generated by Django 3.0.3 on 2021-03-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0008_auto_20210301_2303'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagen',
            managers=[
            ],
        ),
    ]
