# Generated by Django 3.0.3 on 2021-03-02 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0009_auto_20210301_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='referencia',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID para referenciar en el texto'),
        ),
    ]
