# Generated by Django 3.0.3 on 2021-03-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0011_auto_20210301_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='referencia',
        ),
    ]
