# Generated by Django 3.0.3 on 2021-03-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0012_remove_imagen_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='content',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='fase',
        ),
        migrations.AddField(
            model_name='componente',
            name='pie',
            field=models.TextField(blank=True, default='', max_length=2500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
    ]
