# Generated by Django 3.0.3 on 2021-03-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0014_auto_20210322_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Módulo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('tipo', models.CharField(choices=[(1, 'Tipo 1'), (2, 'Tipo 2'), (3, 'Tipo 3')], max_length=1500, verbose_name='Tipo de módulo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='inicio',
        ),
        migrations.AddField(
            model_name='etapa',
            name='fin',
            field=models.PositiveIntegerField(default=99, verbose_name='fin'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='inicio',
            field=models.PositiveIntegerField(default=1, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Fase'),
        ),
    ]
