# Generated by Django 3.0.3 on 2021-03-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0016_auto_20210328_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='tipo',
            field=models.CharField(choices=[(1, 'Tipo 1'), (2, 'Tipo 2'), (3, 'Tipo 3')], max_length=500, verbose_name='Tipo de módulo'),
        ),
    ]
