# Generated by Django 3.0.3 on 2021-03-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0018_auto_20210329_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='modulo',
            name='t_aprob_edificable',
            field=models.BooleanField(default=False, verbose_name='¿Incluye aprovechamiento edificable?'),
        ),
    ]
