# Generated by Django 3.0.3 on 2021-03-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0019_auto_20210330_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='t_aprob_edificable',
        ),
        migrations.AddField(
            model_name='modulo',
            name='t_aprov_edificable',
            field=models.BooleanField(default=False, verbose_name='Incluye aprovechamiento edificable'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='t_aprov_lineal',
            field=models.BooleanField(default=False, verbose_name='Incluye aprovechamiento líneal'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='t_areas_verdes',
            field=models.BooleanField(default=False, verbose_name='Incluye áreas verdes ornamentales'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='t_obras',
            field=models.BooleanField(default=False, verbose_name='Incluye obras provisionales temporales'),
        ),
    ]
