# Generated by Django 3.0.3 on 2021-03-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0020_auto_20210330_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='title',
            field=models.CharField(max_length=2500, verbose_name='Módulo'),
        ),
    ]
