# Generated by Django 3.0.3 on 2021-04-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0021_auto_20210330_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['-created'], 'verbose_name': 'Componente', 'verbose_name_plural': 'Componentes'},
        ),
        migrations.AddField(
            model_name='modulo',
            name='t_base',
            field=models.BooleanField(default=True, verbose_name='Base'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='title',
            field=models.CharField(max_length=2500, verbose_name='Componente'),
        ),
    ]
