# Generated by Django 3.0.3 on 2021-04-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0023_modulo_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Componente'),
        ),
    ]
