# Generated by Django 3.0.3 on 2021-04-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0024_auto_20210416_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='title',
            field=models.CharField(max_length=2, verbose_name='Etapa'),
        ),
    ]
