# Generated by Django 3.0.3 on 2021-04-21 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0025_auto_20210417_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='fase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase'),
        ),
    ]
