# Generated by Django 3.0.3 on 2021-04-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0026_etapa_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='etapas',
            field=models.ManyToManyField(to='cap2.Etapa', verbose_name='Selecciona las etapas'),
        ),
    ]
