# Generated by Django 3.0.3 on 2021-04-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0027_modulo_etapas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='title',
            field=models.PositiveIntegerField(max_length=2, verbose_name='Etapa'),
        ),
    ]
