# Generated by Django 3.0.3 on 2021-04-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0029_auto_20210420_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='title',
            field=models.CharField(max_length=280, verbose_name='Componente'),
        ),
    ]
