# Generated by Django 3.0.3 on 2021-04-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0030_auto_20210421_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['fase', 'title'], 'verbose_name': 'Etapa', 'verbose_name_plural': 'Etapas'},
        ),
    ]
