# Generated by Django 3.0.3 on 2021-04-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0031_auto_20210422_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={'ordering': ['created'], 'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
    ]
