# Generated by Django 3.0.3 on 2021-08-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0032_auto_20210422_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='t_actividad',
            field=models.BooleanField(default=False, verbose_name='Incluye actividades de servicios, comerciales, recreativas o culturales (solo aplica en operación)'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='t_aguas',
            field=models.BooleanField(default=False, verbose_name='Incluye plantas de tratamiento y manejo de aguas residuales (solo aplica en mantenimiento)'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='t_hospedaje',
            field=models.BooleanField(default=False, verbose_name='Incluye actividades de alojamiento a visitantes (solo aplica para operación)'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='t_plantas',
            field=models.BooleanField(default=False, verbose_name='Incluye planta potabilizadora (solo aplica en mantenimiento)'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='t_semipermanentes',
            field=models.BooleanField(default=False, verbose_name='Incluye obras provisionales semipermanentes'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='t_via_senderos',
            field=models.BooleanField(default=False, verbose_name='Incluye vialidades y senderos'),
        ),
    ]
