# Generated by Django 3.0.3 on 2021-03-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadprovicional',
            name='title',
            field=models.CharField(max_length=1500, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='edificacionprovicional',
            name='description',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='edificacionprovicional',
            name='title',
            field=models.CharField(max_length=1500, verbose_name='Edificación en obras provisionales'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='title',
            field=models.CharField(max_length=1500, verbose_name='Nombre de la máquina'),
        ),
    ]
