# Generated by Django 3.0.3 on 2021-03-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0002_auto_20210301_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edificacionprovicional',
            options={'ordering': ['title'], 'verbose_name': 'Edificacion provisional', 'verbose_name_plural': 'Edificaciones provisionales'},
        ),
        migrations.AlterField(
            model_name='unidad',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Unidad de medida'),
        ),
    ]
