# Generated by Django 3.0.3 on 2021-03-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0003_auto_20210308_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadprovicional',
            options={'ordering': ['title'], 'verbose_name': 'Actividad provisional', 'verbose_name_plural': 'Actividades provisionales'},
        ),
    ]
