# Generated by Django 3.0.3 on 2021-03-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0004_auto_20210309_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Tipo de agua',
                'verbose_name_plural': 'Tipo de agua',
                'ordering': ['title'],
            },
        ),
    ]
