# Generated by Django 3.0.3 on 2021-03-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0005_tipoagua'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieFlores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1500, verbose_name='Nombre común')),
                ('familia', models.CharField(max_length=1500, verbose_name='Familia')),
                ('especie', models.CharField(max_length=1500, verbose_name='Especie')),
                ('forma', models.CharField(max_length=1500, verbose_name='Forma biológica')),
                ('rescate', models.CharField(choices=[('Individuos', 'Individuos'), ('Semillas', 'Semillas'), ('Estacas', 'Estacas'), ('Individuos o semillas', 'Individuos o semillas'), ('Individuos, semillas o estacas', 'Individuos, semillas o estacas')], max_length=1500, verbose_name='Criterios para rescate')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Tipo de especie florística',
                'verbose_name_plural': 'Tipo de especie florística',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InsumosLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=5000, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Tipo de insumo',
                'verbose_name_plural': 'Tipo de insumo',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SustanciasQuimicasP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Tipo de sustancia',
                'verbose_name_plural': 'Tipo de sustancia',
                'ordering': ['title'],
            },
        ),
    ]
