# Generated by Django 3.0.3 on 2021-03-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0007_auto_20210330_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumoslista',
            options={'ordering': ['title'], 'verbose_name': 'Lista de insumos de construcción', 'verbose_name_plural': 'Lista de insumos de construcción'},
        ),
        migrations.AlterModelOptions(
            name='tipoagua',
            options={'ordering': ['title'], 'verbose_name': 'Lista de tipos de agua', 'verbose_name_plural': 'Lista de tipos de agua'},
        ),
        migrations.AlterField(
            model_name='insumoslista',
            name='title',
            field=models.TextField(max_length=5000, verbose_name='Insumo'),
        ),
    ]
