# Generated by Django 3.0.3 on 2021-04-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0008_auto_20210330_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquina',
            options={'ordering': ['tipo'], 'verbose_name': 'Lista de maquinaría', 'verbose_name_plural': 'Lista de maquinaría'},
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='title',
        ),
        migrations.AddField(
            model_name='maquina',
            name='combustible',
            field=models.CharField(choices=[('Diésel', 'Diésel'), ('Electricidad', 'Electricidad'), ('Eólica', 'Eólica'), ('Gas LP', 'Gas LP'), ('Gas natural', 'Gas naturals'), ('Gasolina', 'Gasolina'), ('Solar', 'Solar')], default='Gasolina', max_length=200, verbose_name='Combustible/energía'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(default='', max_length=1500, verbose_name='Tipo'),
        ),
    ]
