# Generated by Django 3.0.3 on 2021-04-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0009_auto_20210405_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='hp',
            field=models.FloatField(default=0.0, verbose_name='KW-h'),
        ),
    ]
