# Generated by Django 3.0.3 on 2021-04-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0010_maquina_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='kwh',
            field=models.FloatField(default=0.0, verbose_name='KW-h'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='hp',
            field=models.FloatField(default=0.0, verbose_name='hp'),
        ),
    ]
