# Generated by Django 3.0.3 on 2021-04-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0030_auto_20210409_0514'),
        ('miscelanea', '0011_auto_20210405_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActividadProvicional',
            new_name='ActividadProvisional',
        ),
        migrations.RenameModel(
            old_name='EdificacionProvicional',
            new_name='EdificacionProvisional',
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['title'], 'verbose_name': 'Lista de unidades', 'verbose_name_plural': 'Lista de unidades'},
        ),
    ]
