# Generated by Django 3.0.3 on 2021-04-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0012_auto_20210409_0514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadprovisional',
            options={'ordering': ['title'], 'verbose_name': 'Lista de actividades provisionales', 'verbose_name_plural': 'Lista de actividades provisionales'},
        ),
    ]
