# Generated by Django 3.0.3 on 2021-04-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0013_auto_20210413_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaProcesoConstructivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=280, verbose_name='Proceso constructivo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de procesos constructivos',
                'verbose_name_plural': 'Lista de procesos constructivos',
                'ordering': ['proceso'],
            },
        ),
        migrations.CreateModel(
            name='ListaTipoResiduos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de tipos de residuos',
                'verbose_name_plural': 'Lista de tipos de residuos',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='TipoAguaResidual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de tipos de agua residuales',
                'verbose_name_plural': 'Lista de tipos de agua residuales',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='edificacionprovisional',
            options={'ordering': ['title'], 'verbose_name': 'Lista de obras o edificaciones provisionales temporales', 'verbose_name_plural': 'Lista de obras o edificaciones provisionales temporales'},
        ),
        migrations.AddField(
            model_name='listatipopersonal',
            name='descripcion',
            field=models.CharField(default='', max_length=280, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='listatipopersonal',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo'),
        ),
    ]
