# Generated by Django 3.0.3 on 2021-04-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0014_auto_20210416_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumoslista',
            name='unidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.Unidad'),
        ),
        migrations.AddField(
            model_name='sustanciasquimicasp',
            name='unidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.Unidad'),
        ),
        migrations.AlterField(
            model_name='insumoslista',
            name='title',
            field=models.TextField(max_length=300, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='description',
            field=models.TextField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Unidad de medida'),
        ),
    ]
