# Generated by Django 3.0.3 on 2021-04-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0015_auto_20210416_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoagua',
            options={'ordering': ['tipo'], 'verbose_name': 'Lista de tipos de agua', 'verbose_name_plural': 'Lista de tipos de agua'},
        ),
        migrations.AlterModelOptions(
            name='tipoaguaresidual',
            options={'ordering': ['tipo'], 'verbose_name': 'Lista de tipos de agua residuales', 'verbose_name_plural': 'Lista de tipos de agua residuales'},
        ),
        migrations.RenameField(
            model_name='tipoagua',
            old_name='title',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='tipoaguaresidual',
            old_name='title',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='listasisconstructivo',
            name='sistema',
            field=models.CharField(max_length=300, verbose_name='Sistema constructivo'),
        ),
    ]
