# Generated by Django 3.0.3 on 2021-04-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0016_auto_20210416_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='listatiporesiduos',
            name='biologico',
            field=models.BooleanField(default=False, verbose_name='Biologico infeccioso'),
        ),
        migrations.AddField(
            model_name='listatiporesiduos',
            name='corrosivo',
            field=models.BooleanField(default=False, verbose_name='Corrosivo'),
        ),
        migrations.AddField(
            model_name='listatiporesiduos',
            name='edo_fisico',
            field=models.CharField(choices=[('Sólido', 'Sólido'), ('Líquido', 'Líquido'), ('Gaseoso', 'Gaseoso')], default='Sólido', max_length=15, verbose_name='Estado físico'),
        ),
        migrations.AddField(
            model_name='listatiporesiduos',
            name='explosivo',
            field=models.BooleanField(default=False, verbose_name='Explosivo'),
        ),
        migrations.AddField(
            model_name='listatiporesiduos',
            name='inflamable',
            field=models.BooleanField(default=False, verbose_name='Inflamable'),
        ),
        migrations.AddField(
            model_name='listatiporesiduos',
            name='reactivo',
            field=models.BooleanField(default=False, verbose_name='Reactivo'),
        ),
        migrations.AddField(
            model_name='listatiporesiduos',
            name='toxico',
            field=models.BooleanField(default=False, verbose_name='Toxico'),
        ),
    ]
