# Generated by Django 3.0.3 on 2021-04-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0017_auto_20210416_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaTiposAprovechamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de aprovechamiento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de tipos de aprovechamiento',
                'verbose_name_plural': 'Lista de tipos de aprovechamiento',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='ListaTiposCobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de cobertura')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de tipos de cobertura y abreviaturas',
                'verbose_name_plural': 'Lista de tipos de cobertura y abreviaturas',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='ListaTiposConsEdif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de cobertura')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de tipos de construcción-edificación',
                'verbose_name_plural': 'Lista de tipos de construcción-edificación',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='ListaZonificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=100, verbose_name='Zona')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de zonificación y abreviaturas',
                'verbose_name_plural': 'Lista de zonificación y abreviaturas',
                'ordering': ['zona'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoTierra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Catálogo de desmonte, despalme, excavación y relleno',
                'verbose_name_plural': 'Catálogo de desmonte, despalme, excavación y relleno',
                'ordering': ['tipo'],
            },
        ),
    ]
