# Generated by Django 3.0.3 on 2021-04-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0018_listatiposaprovechamiento_listatiposcobertura_listatiposconsedif_listazonificacion_movimientotierra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrasLineales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo de obra lineal')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de obras lineales',
                'verbose_name_plural': 'Lista de obras lineales',
                'ordering': ['tipo'],
            },
        ),
    ]
