# Generated by Django 3.0.3 on 2021-04-19 00:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0019_obraslineales'),
    ]

    operations = [
        migrations.AddField(
            model_name='listasisconstructivo',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Descipción del sistema constructivo'),
        ),
    ]
