# Generated by Django 3.0.3 on 2021-04-19 02:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0020_listasisconstructivo_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listasisconstructivo',
            name='content',
        ),
        migrations.CreateModel(
            name='ListaSisConstructivoFiguras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='null', upload_to='sistemasconstructivos-fig', verbose_name='Figura')),
                ('pie', models.CharField(max_length=300, verbose_name='pie de figura')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('sistema', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaSisConstructivo')),
            ],
            options={
                'verbose_name': 'Figuras - Descripción del sistema constructivo',
                'verbose_name_plural': 'Figuras - Descripción del sistema constructivo',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DescripcionSisConstructivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='Descipción del sistema constructivo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('sistema', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaSisConstructivo')),
            ],
            options={
                'verbose_name': 'Descripción de sistemas constructivos',
                'verbose_name_plural': 'Descripción de sistemas constructivos',
                'ordering': ['sistema'],
            },
        ),
    ]
