# Generated by Django 3.0.3 on 2021-04-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0021_auto_20210418_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='listasisconstructivofiguras',
            name='descripcion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.DescripcionSisConstructivo'),
        ),
    ]
