# Generated by Django 3.0.3 on 2021-04-21 07:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0022_listasisconstructivofiguras_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificacionprovisional',
            name='description',
        ),
        migrations.AlterField(
            model_name='unidad',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Unidad de medida'),
        ),
    ]
