# Generated by Django 3.0.3 on 2021-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0024_auto_20210421_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Unidad de medida'),
        ),
    ]
