# Generated by Django 3.0.3 on 2021-04-23 00:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0027_procconstructivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listatiposaprovechamiento',
            options={'ordering': ['title'], 'verbose_name': 'Lista de tipos de aprovechamiento', 'verbose_name_plural': 'Lista de tipos de aprovechamiento'},
        ),
        migrations.RenameField(
            model_name='listatiposaprovechamiento',
            old_name='tipo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='listatiposaprovechamiento',
            name='subtipo',
            field=models.CharField(choices=[('Edificable', 'Edificable'), ('No edificable', 'No edificable')], default='Edificable', max_length=15, verbose_name='Seleccionar el subtipo'),
        ),
        migrations.AlterField(
            model_name='procconstructivo',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Descripción del proceso constructivo'),
        ),
    ]
