# Generated by Django 3.0.3 on 2021-04-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0028_auto_20210422_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listatiporesiduos',
            options={'ordering': ['tipo'], 'verbose_name': 'Lista de tipos de residuos tóxicos', 'verbose_name_plural': 'Lista de tipos de residuos tóxicos'},
        ),
        migrations.AddField(
            model_name='movimientotierra',
            name='unidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.Unidad'),
        ),
        migrations.AlterField(
            model_name='listatiporesiduos',
            name='biologico',
            field=models.BooleanField(default=False, verbose_name='Biológico infeccioso'),
        ),
        migrations.AlterField(
            model_name='listatiporesiduos',
            name='toxico',
            field=models.BooleanField(default=False, verbose_name='Tóxico'),
        ),
        migrations.CreateModel(
            name='ListaTipoResiduosSolidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('unidad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.Unidad')),
            ],
            options={
                'verbose_name': 'Lista de tipos de residuos sólidos',
                'verbose_name_plural': 'Lista de tipos de residuos sólidos',
                'ordering': ['tipo'],
            },
        ),
    ]
