# Generated by Django 3.0.3 on 2021-05-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0029_auto_20210422_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadofloristico',
            name='rescate',
            field=models.CharField(choices=[('Individuos', 'Individuos'), ('Semillas', 'Semillas'), ('Estacas', 'Estacas'), ('Esquejes', 'Esquejes'), ('Individuos o semillas', 'Individuos o semillas'), ('Individuos, semillas o estacas', 'Individuos, semillas o estacas'), ('Individuos, semillas o esquejes', 'Individuos, semillas o esquejes')], max_length=1500, verbose_name='Criterios para rescate'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='combustible',
            field=models.CharField(choices=[('Diésel', 'Diésel'), ('Electricidad', 'Electricidad'), ('Eólica', 'Eólica'), ('Gas LP', 'Gas LP'), ('Gas natural', 'Gas natural'), ('Gasolina', 'Gasolina'), ('Solar', 'Solar')], default='Gasolina', max_length=200, verbose_name='Combustible/energía'),
        ),
    ]
