# Generated by Django 3.0.3 on 2021-08-09 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0032_auto_20210422_2055'),
        ('miscelanea', '0030_auto_20210503_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaAct_scrc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=1500, verbose_name='Actividad')),
                ('descripcion', models.CharField(max_length=1500, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista y descripción de actividades de servicios, comerciales, recreativas o culturales',
                'verbose_name_plural': 'Lista y descripción de actividades de servicios, comerciales, recreativas o culturales',
                'ordering': ['actividad'],
            },
        ),
        migrations.CreateModel(
            name='ListaFrecAct_scrc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=1500, verbose_name='Actividad')),
                ('descripcion', models.CharField(max_length=1500, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de actividades de visitantes',
                'verbose_name_plural': 'Lista de actividades de visitantes',
                'ordering': ['actividad'],
            },
        ),
        migrations.CreateModel(
            name='ListaTipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=500, verbose_name='Tipo de vehículo')),
                ('descripcion', models.CharField(max_length=1200, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de tipo de vehículos',
                'verbose_name_plural': 'Lista de tipo de vehículos',
                'ordering': ['tipo'],
            },
        ),
        migrations.AddField(
            model_name='insumoslista',
            name='fase',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='cap2.Fase'),
        ),
        migrations.CreateModel(
            name='ListaVehiculoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=500, verbose_name='Vehículo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('tipo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaTipoVehiculo')),
            ],
            options={
                'verbose_name': 'Lista de vehículos por tipo',
                'verbose_name_plural': 'Lista de vehículos por tipo ',
                'ordering': ['vehiculo'],
            },
        ),
    ]
