# Generated by Django 3.0.3 on 2021-08-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0032_auto_20210808_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaActividadesInsEsp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=1500, verbose_name='Actividad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de actividades en instalaciones especiales',
                'verbose_name_plural': 'Lista de actividades en instalaciones especiales',
                'ordering': ['actividad'],
            },
        ),
        migrations.AlterModelOptions(
            name='listaactividades',
            options={'ordering': ['actividad'], 'verbose_name': 'Lista de actividades', 'verbose_name_plural': 'Lista de actividades'},
        ),
    ]
