# Generated by Django 3.0.3 on 2021-08-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0033_auto_20210808_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumoslista',
            options={'ordering': ['title'], 'verbose_name': 'Lista de insumos', 'verbose_name_plural': 'Lista de insumos'},
        ),
    ]
