# Generated by Django 3.0.3 on 2021-08-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0032_auto_20210422_2055'),
        ('miscelanea', '0035_listatipopersonal_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustanciasquimicasp',
            name='fase',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='cap2.Fase'),
        ),
    ]
