# Generated by Django 3.0.3 on 2021-08-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0037_auto_20210820_0314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListaVehiculoTipo',
            new_name='VehiculoPorTipo',
        ),
    ]
