# Generated by Django 3.0.3 on 2021-08-21 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0038_auto_20210820_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoportipo',
            name='combustible',
            field=models.CharField(choices=[('Diésel', 'Diésel'), ('Gas LP', 'Gas LP'), ('Gas natural', 'Gas natural'), ('Gasolina', 'Gasolina')], default='Gasolina', max_length=200, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculoportipo',
            name='tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaTipoVehiculo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vehiculoportipo',
            name='vehiculo',
            field=models.CharField(max_length=1200, verbose_name='Vehículo'),
        ),
    ]
