# Generated by Django 3.0.3 on 2021-08-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0041_auto_20210823_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listactvisitantes',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='listaact_scrc',
            name='descripcion',
            field=models.CharField(default='', max_length=1500, verbose_name='Descripción'),
        ),
    ]
