# Generated by Django 3.0.3 on 2021-08-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0042_auto_20210823_0323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaActividadesInsEsp',
        ),
        migrations.RemoveField(
            model_name='listaactinsesp',
            name='ins_especial',
        ),
        migrations.DeleteModel(
            name='ListaAreasManejo',
        ),
    ]
