# Generated by Django 3.0.3 on 2021-08-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0032_auto_20210422_2055'),
        ('miscelanea', '0043_auto_20210823_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaactividades',
            name='fase',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='cap2.Fase', verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='residuospeligrosos',
            name='unidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.Unidad', verbose_name='Unidad de medida'),
        ),
    ]
