# Generated by Django 3.0.3 on 2021-09-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0044_auto_20210823_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listatiporesiduossolidos',
            name='tipo',
            field=models.CharField(max_length=240, verbose_name='Tipo'),
        ),
    ]
