# Generated by Django 3.0.3 on 2021-09-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0033_auto_20210824_1221'),
        ('miscelanea', '0045_auto_20210910_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumoslista',
            name='fase',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase'),
        ),
    ]
