# Generated by Django 3.0.3 on 2021-10-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0046_auto_20210919_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listatiposaprovechamiento',
            options={'ordering': ['title'], 'verbose_name': 'Lista de tipos de procesos constructivos', 'verbose_name_plural': 'Lista de tipos de procesos constructivos'},
        ),
        migrations.AlterField(
            model_name='listatiposaprovechamiento',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ProcConstructivo', verbose_name='Tipo de proceso constructivo'),
        ),
    ]
