# Generated by Django 3.0.3 on 2021-10-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0047_auto_20211005_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listatiposaprovechamiento',
            name='subtipo',
            field=models.CharField(choices=[('Edificable', 'Edificable'), ('No edificable', 'No edificable')], default='Edificable', max_length=20, verbose_name='Seleccionar el subtipo'),
        ),
    ]
