# Generated by Django 3.0.3 on 2021-02-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superficieobras',
            name='published',
        ),
    ]
