# Generated by Django 3.0.3 on 2021-03-02 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0001_initial'),
        ('formulario', '0002_remove_superficieobras_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superficieobras',
            name='edificaciones',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.EdificacionProvicional'),
        ),
    ]
