# Generated by Django 3.0.3 on 2021-03-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20210301_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superficieobras',
            name='edificaciones',
            field=models.CharField(max_length=500, verbose_name='Edificaciones en obras provicionales'),
        ),
    ]
