# Generated by Django 3.0.3 on 2021-03-02 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0002_auto_20210301_2107'),
        ('formulario', '0004_auto_20210301_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superficieobras',
            name='edificaciones',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.EdificacionProvicional'),
        ),
    ]
