# Generated by Django 3.0.3 on 2021-03-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_auto_20210309_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='superficieobras',
            name='etapa',
            field=models.CharField(default='Construcción', max_length=20),
        ),
    ]
