# Generated by Django 3.0.3 on 2021-03-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0013_auto_20210308_2331'),
        ('miscelanea', '0004_auto_20210309_0008'),
        ('formulario', '0008_superficieobras_etapa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperficieObras',
            new_name='SuperficieObrasC',
        ),
        migrations.AlterModelOptions(
            name='superficieobrasc',
            options={'ordering': ['-created'], 'verbose_name': 'Superficie de obras provisionales temporales - Construcción', 'verbose_name_plural': 'Superficie de obras provisionales temporales  - Construcción'},
        ),
        migrations.CreateModel(
            name='FrecuenciaActividadesC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(default='Construcción', max_length=20)),
                ('horas', models.IntegerField(verbose_name='Jornadas/fase')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('actividades', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ActividadProvicional')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Componente')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
            ],
            options={
                'verbose_name': 'Frecuencia de actividades de obras provisionales - Construcción',
                'verbose_name_plural': 'Frecuencia de actividades de obras provisionales  - Construcción',
                'ordering': ['-created'],
            },
        ),
    ]
