# Generated by Django 3.0.3 on 2021-03-09 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0005_tipoagua'),
        ('cap2', '0013_auto_20210308_2331'),
        ('formulario', '0009_auto_20210309_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoAguaC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(default='Construcción', max_length=20)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad en m³')),
                ('unidad', models.CharField(default='m³', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Componente')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('tipo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.TipoAgua')),
            ],
            options={
                'verbose_name': 'Consumo de agua - Construcción',
                'verbose_name_plural': 'Consumo de agua - Construcción',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AguasResidualesC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(default='Construcción', max_length=20)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad en m³')),
                ('unidad', models.CharField(default='m³', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Componente')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('tipo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.TipoAgua')),
            ],
            options={
                'verbose_name': 'Generación de aguas residuales - Construcción',
                'verbose_name_plural': 'Generación de aguas residuales - Construcción',
                'ordering': ['-created'],
            },
        ),
    ]
