# Generated by Django 3.0.3 on 2021-03-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0015_auto_20210328_1657'),
        ('formulario', '0010_aguasresidualesc_consumoaguac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aguasresidualesc',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='consumoaguac',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='frecuenciaactividadesc',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='superficieobrasc',
            name='componente',
        ),
        migrations.AddField(
            model_name='aguasresidualesc',
            name='modulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo'),
        ),
        migrations.AddField(
            model_name='consumoaguac',
            name='modulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo'),
        ),
        migrations.AddField(
            model_name='frecuenciaactividadesc',
            name='modulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo'),
        ),
        migrations.AddField(
            model_name='superficieobrasc',
            name='modulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo'),
        ),
    ]
