# Generated by Django 3.0.3 on 2021-03-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0011_auto_20210328_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumoaguac',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='consumoaguac',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='consumoaguac',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='frecuenciaactividadesc',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='frecuenciaactividadesc',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='frecuenciaactividadesc',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='superficieobrasc',
            name='edificaciones',
        ),
        migrations.RemoveField(
            model_name='superficieobrasc',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='superficieobrasc',
            name='modulo',
        ),
        migrations.DeleteModel(
            name='AguasResidualesC',
        ),
        migrations.DeleteModel(
            name='ConsumoAguaC',
        ),
        migrations.DeleteModel(
            name='FrecuenciaActividadesC',
        ),
        migrations.DeleteModel(
            name='SuperficieObrasC',
        ),
    ]
