# Generated by Django 3.0.3 on 2021-03-28 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cap2', '0017_auto_20210328_1732'),
        ('miscelanea', '0006_especieflores_insumoslista_sustanciasquimicasp'),
        ('formulario', '0012_auto_20210328_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperficieObrasC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(default='Construcción', max_length=20)),
                ('superficie', models.IntegerField(verbose_name='Superficie m²')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('edificaciones', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.EdificacionProvicional')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('modulo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
            ],
            options={
                'verbose_name': 'Superficie de obras provisionales temporales - Construcción',
                'verbose_name_plural': 'Superficie de obras provisionales temporales  - Construcción',
                'ordering': ['-created'],
            },
        ),
    ]
