# Generated by Django 3.0.3 on 2021-03-28 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0017_auto_20210328_1732'),
        ('formulario', '0013_superficieobrasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superficieobrasc',
            name='modulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo'),
        ),
    ]
