# Generated by Django 3.0.3 on 2021-03-29 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0017_auto_20210328_1732'),
        ('formulario', '0016_remove_superficieobrasc_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='superficieobrasc',
            name='modulo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo'),
        ),
    ]
