# Generated by Django 3.0.3 on 2021-03-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0021_auto_20210330_1157'),
        ('formulario', '0017_superficieobrasc_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superficieobrasc',
            name='etapa',
        ),
        migrations.AlterField(
            model_name='superficieobrasc',
            name='fase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase'),
        ),
    ]
