# Generated by Django 3.0.3 on 2021-04-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0022_auto_20210401_0237'),
        ('formulario', '0018_auto_20210330_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superficieobrasc',
            old_name='modulo',
            new_name='componente',
        ),
        migrations.CreateModel(
            name='CatForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2500, verbose_name='Nombre del formulario')),
                ('tipo', models.CharField(choices=[('Formulario de datos', 'Formulariode datos'), ('Formulario de texto y figuras', 'Formulario de texto y figuras'), ('Catálogo por fase', 'Catálogo por fase'), ('Catálogo de abreviaturas', 'Catálogo de abreviaturas'), ('Formulario de datos y abreviaturas', 'Formulario de datos y abreviaturas'), ('Catálogo', 'Catálogo')], default='', max_length=100)),
                ('tipo_c', models.CharField(choices=[('1', 'Base (todos)'), ('2', 'Incluye aprovechamiento edificable'), ('3', 'Incluye obras provisionales temporales'), ('4', 'Incluye áreas verdes ornamentales'), ('5', 'Incluye aprovechamiento líneal')], default='1', max_length=10)),
                ('url', models.CharField(blank=True, default='', max_length=2500, verbose_name='url')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fase', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
            ],
            options={
                'verbose_name': 'Formularios y catálogos',
                'verbose_name_plural': 'Formularios y catálogos',
                'ordering': ['-created'],
            },
        ),
    ]
