# Generated by Django 3.0.3 on 2021-04-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0022_auto_20210401_0237'),
        ('formulario', '0021_catform_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='catform',
            name='componente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo'),
        ),
        migrations.AlterField(
            model_name='catform',
            name='tipo',
            field=models.CharField(choices=[('Formulario de datos', 'Formulario de datos'), ('Formulario de texto y figuras', 'Formulario de texto y figuras'), ('Catálogo por fase', 'Catálogo por fase'), ('Catálogo de abreviaturas', 'Catálogo de abreviaturas'), ('Formulario de datos y abreviaturas', 'Formulario de datos y abreviaturas'), ('Catálogo', 'Catálogo'), ('PNG', 'PNG')], default='', max_length=100, verbose_name='tipo de catálogo/formulario'),
        ),
        migrations.AlterField(
            model_name='catform',
            name='tipo_c',
            field=models.CharField(choices=[('1', 'Base (todos)'), ('2', 'Incluye aprovechamiento edificable'), ('3', 'Incluye obras provisionales temporales'), ('4', 'Incluye áreas verdes ornamentales'), ('5', 'Incluye aprovechamiento lineal')], default='1', max_length=10, verbose_name='tipo de componente al que aplica'),
        ),
    ]
