# Generated by Django 3.0.3 on 2021-04-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0023_auto_20210404_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenlocalizacion',
            old_name='modulo',
            new_name='componente',
        ),
    ]
