# Generated by Django 3.0.3 on 2021-04-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0022_auto_20210401_0237'),
        ('formulario', '0026_auto_20210404_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='superficieobrasc',
            name='etapa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa'),
        ),
    ]
