# Generated by Django 3.0.3 on 2021-04-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0028_auto_20210404_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenlocalizacionc',
            options={'ordering': ['-created'], 'verbose_name': 'Imagen de localización y tipos de aprovechamiento - Construcción', 'verbose_name_plural': 'Imagen de localización y tipos de aprovechamiento - Construcción'},
        ),
    ]
