# Generated by Django 3.0.3 on 2021-04-09 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0022_auto_20210401_0237'),
        ('formulario', '0029_auto_20210405_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenlocalizacionc',
            name='fase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase'),
        ),
    ]
