# Generated by Django 3.0.3 on 2021-04-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0030_auto_20210409_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catform',
            name='url',
        ),
        migrations.AddField(
            model_name='catform',
            name='nurl',
            field=models.CharField(blank=True, default='', max_length=2500, verbose_name='nombre url'),
        ),
    ]
