# Generated by Django 3.0.3 on 2021-04-16 04:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0024_auto_20210416_0436'),
        ('formulario', '0031_auto_20210413_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frecuenciaactividadesc',
            options={'ordering': ['-created'], 'verbose_name': 'Frecuencia de actividades de obras provisionales', 'verbose_name_plural': 'Frecuencia de actividades de obras provisionales'},
        ),
        migrations.AlterField(
            model_name='frecuenciaactividadesc',
            name='fase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase'),
        ),
        migrations.CreateModel(
            name='DescripcionGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Descipción general del componente para esta etapa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
            ],
            options={
                'verbose_name': 'Descripción general del componente para esta etapa',
                'verbose_name_plural': 'Descripción general del componente para esta etapa',
                'ordering': ['componente', 'etapa'],
            },
        ),
    ]
