# Generated by Django 3.0.3 on 2021-04-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0024_auto_20210416_0436'),
        ('miscelanea', '0014_auto_20210416_0726'),
        ('formulario', '0032_auto_20210416_0436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aguasresidualesc',
            options={'ordering': ['-created'], 'verbose_name': 'Generación de aguas residuales', 'verbose_name_plural': 'Generación de aguas residuales'},
        ),
        migrations.AlterModelOptions(
            name='consumoaguac',
            options={'ordering': ['-created'], 'verbose_name': 'Consumo de agua', 'verbose_name_plural': 'Consumo de agua'},
        ),
        migrations.AlterModelOptions(
            name='superficieobrasc',
            options={'ordering': ['-created'], 'verbose_name': 'Superficie de obras o edificaciones provisionales temporales', 'verbose_name_plural': 'Superficie de obras o edificaciones  provisionales temporales'},
        ),
        migrations.AlterField(
            model_name='aguasresidualesc',
            name='fase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase'),
        ),
        migrations.AlterField(
            model_name='aguasresidualesc',
            name='tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.TipoAguaResidual'),
        ),
        migrations.AlterField(
            model_name='frecuenciaactividadesc',
            name='horas',
            field=models.IntegerField(verbose_name='Jornadas/Etapa'),
        ),
        migrations.AlterField(
            model_name='superficieobrasc',
            name='fase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase'),
        ),
        migrations.CreateModel(
            name='PersonalRequerido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('flor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListadoFloristico')),
            ],
            options={
                'verbose_name': 'Listado florístico en el módulo',
                'verbose_name_plural': 'Listado florístico en el módulo',
                'ordering': ['flor'],
            },
        ),
        migrations.CreateModel(
            name='ListadoFloristicoC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('flor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListadoFloristico')),
            ],
            options={
                'verbose_name': 'Listado florístico en el módulo',
                'verbose_name_plural': 'Listado florístico en el módulo',
                'ordering': ['flor'],
            },
        ),
        migrations.CreateModel(
            name='DescripcionGeneralFiguras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='null', upload_to='generales-fig', verbose_name='Figura')),
                ('pie', models.CharField(max_length=300, verbose_name='pie de figura')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
            ],
            options={
                'verbose_name': 'Figuras - Descripción general del componente - Construcción',
                'verbose_name_plural': 'Figuras - Descripción general del componente - Construcción',
                'ordering': ['-created'],
            },
        ),
    ]
