# Generated by Django 3.0.3 on 2021-04-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0033_auto_20210416_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenlocalizacionc',
            name='title',
        ),
    ]
