# Generated by Django 3.0.3 on 2021-04-18 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0018_listatiposaprovechamiento_listatiposcobertura_listatiposconsedif_listazonificacion_movimientotierra'),
        ('formulario', '0034_remove_imagenlocalizacionc_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalrequerido',
            options={'ordering': ['created'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.RemoveField(
            model_name='personalrequerido',
            name='flor',
        ),
        migrations.AddField(
            model_name='personalrequerido',
            name='cobertura',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaTiposCobertura'),
        ),
        migrations.AddField(
            model_name='personalrequerido',
            name='n_personal',
            field=models.IntegerField(default=0, verbose_name='Número de personal'),
        ),
        migrations.AddField(
            model_name='personalrequerido',
            name='personal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaTipoPersonal'),
        ),
    ]
