# Generated by Django 3.0.3 on 2021-04-18 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0025_auto_20210417_1434'),
        ('miscelanea', '0019_obraslineales'),
        ('formulario', '0036_maquinariacobertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrasLinealesLongitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud', models.FloatField(default=0.0, verbose_name='Longitud en Km')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('tipo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ObrasLineales')),
            ],
            options={
                'verbose_name': 'Longitud de obras lineales',
                'verbose_name_plural': 'Longitud de obras lineales',
                'ordering': ['created'],
            },
        ),
    ]
