# Generated by Django 3.0.3 on 2021-04-19 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0025_auto_20210417_1434'),
        ('formulario', '0038_catform_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_aprov_total', models.FloatField(verbose_name='Superficie aprovechable total (ha)')),
                ('sup_edi', models.FloatField(verbose_name='Superficie edificable (ha)')),
                ('sup_const_no_edi', models.FloatField(verbose_name='Superficie a construir no edificable (ha)')),
                ('nivel_max', models.IntegerField(verbose_name='Niveles máximos construidos')),
                ('zonificacion', models.CharField(max_length=30, verbose_name='Abreviaturas de las zonificaciones (separaras por comas)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
            ],
            options={
                'verbose_name': 'Datos generales del componente',
                'verbose_name_plural': 'Datos generales del componente',
                'ordering': ['-created'],
            },
        ),
    ]
