# Generated by Django 3.0.3 on 2021-04-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0039_datosgeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripciongeneral',
            name='duracion',
            field=models.TextField(default='', max_length=30, verbose_name='Duración de las obras o actividades'),
        ),
    ]
