# Generated by Django 3.0.3 on 2021-04-20 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0021_auto_20210418_2112'),
        ('cap2', '0025_auto_20210417_1434'),
        ('formulario', '0040_descripciongeneral_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeleccionSistemasConstructivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('sistemas', models.ManyToManyField(to='miscelanea.DescripcionSisConstructivo', verbose_name='Sistemas construcitivos')),
            ],
            options={
                'verbose_name': 'Selección de sistemas constructivos',
                'verbose_name_plural': 'Selección de sistemas constructivos',
                'ordering': ['-created'],
            },
        ),
    ]
