# Generated by Django 3.0.3 on 2021-04-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0022_listasisconstructivofiguras_descripcion'),
        ('cap2', '0025_auto_20210417_1434'),
        ('formulario', '0041_seleccionsistemasconstructivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionProcesosConstructivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('proceso_constructivo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaProcesoConstructivo')),
            ],
        ),
    ]
