# Generated by Django 3.0.3 on 2021-04-20 03:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0042_descripcionprocesosconstructivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descripcionprocesosconstructivos',
            options={'ordering': ['-id'], 'verbose_name': 'Descripción de procesos constructivos', 'verbose_name_plural': 'Descripción de procesos constructivos'},
        ),
        migrations.AddField(
            model_name='descripcionprocesosconstructivos',
            name='contenido',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Descipción de proceso construcivo'),
        ),
    ]
