# Generated by Django 3.0.3 on 2021-04-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0022_listasisconstructivofiguras_descripcion'),
        ('cap2', '0025_auto_20210417_1434'),
        ('formulario', '0043_auto_20210419_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinariaZonificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_prot', models.IntegerField(default=0, verbose_name='Número de horas por zonificación Protección - PROT')),
                ('n_rest', models.IntegerField(default=0, verbose_name='Número de horas por zonificación Uso restringido -  REST')),
                ('n_apro', models.IntegerField(default=0, verbose_name='Número de horas por zonificación Uso Aprovechamiento controlado - APRO')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('maquinaria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.Maquina')),
            ],
            options={
                'verbose_name': 'Maquinaria por zonificación',
                'verbose_name_plural': 'Maquinaria por zonificación',
                'ordering': ['created'],
            },
        ),
        migrations.AlterModelOptions(
            name='personalrequerido',
            options={'ordering': ['created'], 'verbose_name': 'Personal requerido por zonificación', 'verbose_name_plural': 'Personal requerido por zonificación'},
        ),
        migrations.RemoveField(
            model_name='personalrequerido',
            name='n_personal',
        ),
        migrations.AddField(
            model_name='personalrequerido',
            name='n_apro',
            field=models.IntegerField(default=0, verbose_name='Número de personal por zonificación Uso Aprovechamiento controlado - APRO'),
        ),
        migrations.AddField(
            model_name='personalrequerido',
            name='n_prot',
            field=models.IntegerField(default=0, verbose_name='Número de personal por zonificación Protección - PROT'),
        ),
        migrations.AddField(
            model_name='personalrequerido',
            name='n_rest',
            field=models.IntegerField(default=0, verbose_name='Número de personal por zonificación Uso restringido -  REST'),
        ),
        migrations.AlterField(
            model_name='consumoaguac',
            name='fase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase'),
        ),
        migrations.DeleteModel(
            name='MaquinariaCobertura',
        ),
    ]
