# Generated by Django 3.0.3 on 2021-04-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0045_auto_20210420_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripciongeneral',
            name='duracion',
            field=models.PositiveIntegerField(default=1, verbose_name='Días de duración de las obras o actividades en la etapa'),
        ),
    ]
