# Generated by Django 3.0.3 on 2021-04-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0026_auto_20210421_1437'),
        ('formulario', '0046_auto_20210421_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleccionsistemasconstructivos',
            name='sistemas',
            field=models.ManyToManyField(to='miscelanea.SisConstructivo', verbose_name='Sistemas construcitivos'),
        ),
    ]
