# Generated by Django 3.0.3 on 2021-04-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0048_seleccionprocesosconstructivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seleccionprocesosconstructivos',
            options={'ordering': ['-created'], 'verbose_name': 'Selección de procesos constructivos', 'verbose_name_plural': 'Selección de procesos constructivos'},
        ),
    ]
