# Generated by Django 3.0.3 on 2021-04-29 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0032_auto_20210422_2055'),
        ('miscelanea', '0029_auto_20210422_2055'),
        ('formulario', '0049_auto_20210422_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumosZonificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_prot', models.IntegerField(default=0, verbose_name='Cantidad por zonificación Protección - PROT')),
                ('n_rest', models.IntegerField(default=0, verbose_name='Cantidad por zonificación Uso restringido -  REST')),
                ('n_apro', models.IntegerField(default=0, verbose_name='Cantidad por zonificación Uso Aprovechamiento controlado - APRO')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('insumo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.InsumosLista')),
            ],
            options={
                'verbose_name': 'Insumos requeridos por zonificación',
                'verbose_name_plural': 'Insumos requeridos por zonificación',
                'ordering': ['created'],
            },
        ),
    ]
