# Generated by Django 3.0.3 on 2021-05-03 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0030_auto_20210503_0017'),
        ('cap2', '0032_auto_20210422_2055'),
        ('formulario', '0050_insumoszonificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalrequerido',
            name='cobertura',
        ),
        migrations.CreateModel(
            name='MovimientoTierraZonificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_prot', models.IntegerField(default=0, verbose_name='Cantidad por zonificación Protección - PROT')),
                ('n_rest', models.IntegerField(default=0, verbose_name='Cantidad por zonificación Uso restringido -  REST')),
                ('n_apro', models.IntegerField(default=0, verbose_name='Cantidad por zonificación Uso Aprovechamiento controlado - APRO')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('zonificacion', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.MovimientoTierra')),
            ],
            options={
                'verbose_name': 'Desmonte, despalme, excavación y relleno por tipo de zonificación',
                'verbose_name_plural': 'Desmonte, despalme, excavación y relleno por tipo de zonificación',
                'ordering': ['created'],
            },
        ),
    ]
