# Generated by Django 3.0.3 on 2021-08-23 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0044_auto_20210823_1401'),
        ('cap2', '0032_auto_20210422_2055'),
        ('formulario', '0054_insumosrequeridosalmacenados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumosrequeridosalmacenados',
            name='max_almacenado',
            field=models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='0%', max_length=10, verbose_name='Máximo almacenado'),
        ),
        migrations.CreateModel(
            name='UsoSustanciasQuimicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='cantidad')),
                ('max_almacenado', models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='0%', max_length=10, verbose_name='Máximo almacenado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('sustancia', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.SustanciasQuimicasP', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Uso de sustancias químicas peligrosas',
                'verbose_name_plural': 'Uso de sustancias químicas peligrosas',
                'ordering': ['-created'],
            },
        ),
    ]
