# Generated by Django 3.0.3 on 2021-09-09 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0033_auto_20210824_1221'),
        ('miscelanea', '0044_auto_20210823_1401'),
        ('formulario', '0057_aforoalmacenamientovehicular_aforotipovehi_aforotipovehimaxdiario_aforovisitantes_capacidadalmresidu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frecuenciaingresosusespeciales',
            name='residuo',
        ),
        migrations.RemoveField(
            model_name='vehiculosrestrigidoszonificacion',
            name='cobertura',
        ),
        migrations.AddField(
            model_name='frecuenciaingresosusespeciales',
            name='sustancia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.SustanciasQuimicasP', verbose_name='Sustancia química peligrosa'),
        ),
        migrations.AddField(
            model_name='vehiculosrestrigidoszonificacion',
            name='zonificacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaZonificacion'),
        ),
        migrations.CreateModel(
            name='UsoMaquinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.IntegerField(default=0, verbose_name='Horas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('maquinaria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.Maquina', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Uso de maquinaria',
                'verbose_name_plural': 'Uso de maquinaria',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaIngresoResEspeciales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad_veh', models.IntegerField(default=0, verbose_name='Capacidad de almacenamiento')),
                ('viajes_anual', models.IntegerField(default=0, verbose_name='Número de viajes al año')),
                ('viajes_totales', models.IntegerField(default=0, verbose_name='Total de viajes en la etapa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListInsEsp', verbose_name='Instalación especial')),
                ('residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ResiduosPeligrosos', verbose_name='Residuo peligroso')),
            ],
            options={
                'verbose_name': 'Frecuencia de ingreso de residuos peligrosos  en instalaciones especiales',
                'verbose_name_plural': 'Frecuencia de ingreso de residuos peligrosos  en instalaciones especiales',
                'ordering': ['created'],
            },
        ),
    ]
