# Generated by Django 3.0.3 on 2021-09-09 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0044_auto_20210823_1401'),
        ('formulario', '0058_auto_20210908_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculosrestrigidoszonificacion',
            options={'ordering': ['created'], 'verbose_name': 'Selección de vehículos restringidos por zonificación', 'verbose_name_plural': 'Selección de vehículos restringidos por zonificación'},
        ),
        migrations.AlterField(
            model_name='vehiculosrestrigidoszonificacion',
            name='zonificacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaZonificacion', verbose_name='Zonificación'),
        ),
    ]
