# Generated by Django 3.0.3 on 2021-09-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0060_auto_20210910_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catform',
            name='tipo_c',
            field=models.CharField(choices=[('1', 'Base (todos)'), ('2', 'Incluye aprovechamiento edificable'), ('3', 'Incluye obras provisionales temporales'), ('4', 'Incluye áreas verdes ornamentales'), ('5', 'Incluye aprovechamiento lineal'), ('6', 'Incluye obras provisionales semipermanentes'), ('7', 'Incluye vialidades y senderos'), ('8', 'Incluye actividades de alojamiento a visitantes (solo aplica para operación)'), ('9', 'Incluye actividades de servicios, comerciales, recreativas o culturales (solo aplica en operación)'), ('10', 'Incluye plantas de tratamiento y manejo de aguas residuales (solo aplica en mantenimiento)'), ('11', 'Incluye planta potabilizadora (solo aplica en mantenimiento)')], default='1', max_length=10, verbose_name='tipo de componente al que aplica'),
        ),
    ]
