# Generated by Django 3.0.3 on 2021-09-13 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0033_auto_20210824_1221'),
        ('formulario', '0062_catform_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraccionAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozo', models.CharField(max_length=300, verbose_name='Pozo')),
                ('velocidad', models.IntegerField(default=0, verbose_name='Velocidad L/s')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
            ],
            options={
                'verbose_name': 'Velocidad de extracción de agua',
                'verbose_name_plural': 'Velocidad de extracción de agua',
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='ExtracciónAgua',
        ),
    ]
