# Generated by Django 3.0.3 on 2021-09-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0064_auto_20210913_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aforovisitantes',
            name='maximo_diario',
            field=models.IntegerField(default=0, verbose_name='Máximo de visitantes diarios'),
        ),
        migrations.AlterField(
            model_name='aforovisitantes',
            name='promedio_diario',
            field=models.IntegerField(default=0, verbose_name='Promedio de visitantes diarios'),
        ),
    ]
