# Generated by Django 3.0.3 on 2021-09-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0045_auto_20210910_0112'),
        ('formulario', '0065_auto_20210913_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aforotipovehi',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Horas/etapa'),
        ),
        migrations.AlterField(
            model_name='aforovisitantes',
            name='actividad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListActVisitantes', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='capacidadalmsustanciasespeciales',
            name='recargas',
            field=models.IntegerField(default=0, verbose_name='Número de recargas al año'),
        ),
        migrations.AlterField(
            model_name='ocupacionaloja',
            name='huespedes_etapa',
            field=models.IntegerField(default=0, verbose_name='Número de huéspedes por etapa'),
        ),
    ]
