# Generated by Django 3.0.3 on 2021-09-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0045_auto_20210910_0112'),
        ('formulario', '0066_auto_20210914_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinariaviajesesp',
            options={'ordering': ['-created'], 'verbose_name': 'Maquinaria y viajes para el suministro de sustancias', 'verbose_name_plural': 'Maquinaria y viajes para el suministro de sustancias'},
        ),
        migrations.AlterField(
            model_name='aforotipovehimaxdiario',
            name='vehiculo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaTipoVehiculo', verbose_name='Tipo de vehículo'),
        ),
        migrations.AlterField(
            model_name='maquinariaviajesesp',
            name='aceites',
            field=models.IntegerField(default=0, verbose_name='Aceites (L)'),
        ),
        migrations.AlterField(
            model_name='ocupacionaloja',
            name='cobertura',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaTiposCobertura', verbose_name='Cobertura'),
        ),
        migrations.AlterField(
            model_name='ocupacionaloja',
            name='oferta',
            field=models.CharField(max_length=500, verbose_name='Oferta de alojamiento'),
        ),
    ]
