# Generated by Django 3.0.3 on 2021-09-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0045_auto_20210910_0112'),
        ('cap2', '0033_auto_20210824_1221'),
        ('formulario', '0067_auto_20210914_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientoAguasResiduales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='L/s')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
                ('ptar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscelanea.ListaPTAR', verbose_name='PTAR')),
            ],
            options={
                'verbose_name': 'Tratamiento de aguas residuales por PTAR',
                'verbose_name_plural': 'Tratamiento de aguas residuales por PTAR',
                'ordering': ['created'],
            },
        ),
    ]
