# Generated by Django 3.0.3 on 2021-09-22 04:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0033_auto_20210824_1221'),
        ('formulario', '0068_tratamientoaguasresiduales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaltransportado',
            options={'ordering': ['created'], 'verbose_name': 'Personal transportado mínimo-máximo diario', 'verbose_name_plural': 'Personal transportado mínimo-máximo'},
        ),
        migrations.CreateModel(
            name='DescripcionOpeManObrasTemporales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Descripción de la operación y mantenimiento de las obras provisionales temporales del componente para esta etapa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
            ],
            options={
                'verbose_name': 'Descripción de la operación y mantenimiento de las obras provisionales temporales',
                'verbose_name_plural': 'Descripción de la operación y mantenimiento de las obras provisionales temporales',
                'ordering': ['componente', 'etapa'],
            },
        ),
        migrations.CreateModel(
            name='DescripcionObrasTemporales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Descripción de las obras provisionales temporales del componente para esta etapa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
            ],
            options={
                'verbose_name': 'Descripción de las obras provisionales temporales',
                'verbose_name_plural': 'Descripción de las obras provisionales temporales',
                'ordering': ['componente', 'etapa'],
            },
        ),
    ]
