# Generated by Django 3.0.3 on 2022-02-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0070_procesosconstructivoszonificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procesosconstructivoszonificacion',
            options={'ordering': ['created'], 'verbose_name': 'Procesos constructivos por zonificación', 'verbose_name_plural': 'Procesos constructivos por zonificación'},
        ),
    ]
