from django.urls import path
from . import views
from .views import * #CatalogosPageView,MaquinaListView, MaquinaCreate, MaquinaUpdate,
catalogos_patterns = ([
    path('', CatalogosPageView.as_view(), name='catalogos'),
    path('componentes/', ModuloListView.as_view(), name='componentes'),
    path('componente-create/',ModuloCreate.as_view(),name='componente-create'),
    path('componente-update/<int:pk>/',ModuloUpdate.as_view(),name='componente-update'),
    path('maquinas/', MaquinaListView.as_view(), name='maquinas'),
    path('maquina-create/',MaquinaCreate.as_view(),name='maquina-create'),
    path('maquina-update/<int:pk>/',MaquinaUpdate.as_view(),name='maquina-update'),
    path('unidades/', UnidadListView.as_view(), name='unidades'),
    path('unidad-create/',UnidadCreate.as_view(),name='unidad-create'),
    path('unidad-update/<int:pk>/',UnidadUpdate.as_view(),name='unidad-update'),
    path('edificaciones/', EdiProvisionalListView.as_view(), name='edificaciones'),
    path('edificio-create/',EdiProvisionalCreate.as_view(),name='edificio-create'),
    path('edificio-update/<int:pk>/',EdiProvisionalUpdate.as_view(),name='edificio-update'),
    path('actividades/', ActProvisionalListView.as_view(), name='actividades'),
    path('actividad-create/',ActProvisionalCreate.as_view(),name='actividad-create'),
    path('actividad-update/<int:pk>/',ActProvisionalUpdate.as_view(),name='actividad-update'),
    path('insumos/', InsumosListaListView.as_view(), name='insumos'),
    path('insumo-create/',InsumosListaCreate.as_view(),name='insumo-create'),
    path('insumo-update/<int:pk>/',InsumosListaUpdate.as_view(),name='insumo-update'),
    path('quimicas/', SustanciasQuimicasPListView.as_view(), name='quimicas'),
    path('quimica-create/',SustanciasQuimicasPCreate.as_view(),name='quimica-create'),
    path('quimica-update/<int:pk>/',SustanciasQuimicasPUpdate.as_view(),name='quimica-update'),
    path('flores/', ListadoFloristicoListView.as_view(), name='flores'),
    path('flor-create/',ListadoFloristicoCreate.as_view(),name='flor-create'),
    path('flor-update/<int:pk>/',ListadoFloristicoUpdate.as_view(),name='flor-update'),
    path('personal/', ListaTipoPersonalListView.as_view(), name='personal'),
    path('personal-create/',ListaTipoPersonalCreate.as_view(),name='personal-create'),
    path('personal-update/<int:pk>/',ListaTipoPersonalUpdate.as_view(),name='personal-update'),
    path('personal/', ListaTipoPersonalListView.as_view(), name='personal'),
    path('personal-create/',ListaTipoPersonalCreate.as_view(),name='personal-create'),
    path('personal-update/<int:pk>/',ListaTipoPersonalUpdate.as_view(),name='personal-update'),
    path('sistema/', ListaSisConstructivoListView.as_view(), name='sistema'),
    path('sistema-create/',ListaSisConstructivoCreate.as_view(),name='sistema-create'),
    path('sistema-update/<int:pk>/',ListaSisConstructivoUpdate.as_view(),name='sistema-update'),

    path('descsistema/', DescripcionSisConstructivoListView.as_view(), name='descsistema'),
    path('descsistema-create/',DescripcionSisConstructivoCreate.as_view(),name='descsistema-create'),
    path('descsistema-update/<int:pk>/',DescripcionSisConstructivoUpdate.as_view(),name='descsistema-update'),

    path('sistemasfiguras-create/<int:pk>/',ListaSisConstructivoFigurasCreate.as_view(),name='sistemasfiguras-create'),
    path('sistemasfiguras-update/<int:pk>/',ListaSisConstructivoFigurasUpdate.as_view(),name='sistemasfiguras-update'),
    path('procesos/', ListaProcesoConstructivoListView.as_view(), name='procesos'),
    path('proceso-create/',ListaProcesoConstructivoCreate.as_view(),name='proceso-create'),
    path('proceso-update/<int:pk>/',ListaProcesoConstructivoUpdate.as_view(),name='proceso-update'),
    path('residuos/', ListaTipoResiduosListView.as_view(), name='residuos'),
    path('residuo-create/',ListaTipoResiduosCreate.as_view(),name='residuo-create'),
    path('residuo-update/<int:pk>/',ListaTipoResiduosUpdate.as_view(),name='residuo-update'),
    path('tagua/', TipoAguaListView.as_view(), name='tagua'),
    path('tagua-create/',TipoAguaCreate.as_view(),name='tagua-create'),
    path('tagua-update/<int:pk>/',TipoAguaUpdate.as_view(),name='tagua-update'),
    path('tagresidual/', TipoAguaResidualListView.as_view(), name='tagresidual'),
    path('tagresidual-create/',TipoAguaResidualCreate.as_view(),name='tagresidual-create'),
    path('tagresidual-update/<int:pk>/',TipoAguaResidualUpdate.as_view(),name='tagresidual-update'),
    path('aprovechamiento/', ListaTiposAprovechamientoListView.as_view(), name='aprovechamiento'),
    path('aprovechamiento-create/',ListaTiposAprovechamientoCreate.as_view(),name='aprovechamiento-create'),
    path('aprovechamiento-update/<int:pk>/',ListaTiposAprovechamientoUpdate.as_view(),name='aprovechamiento-update'),
    path('cobertura/', ListaTiposCoberturaListView.as_view(), name='cobertura'),
    path('cobertura-create/',ListaTiposCoberturaCreate.as_view(),name='cobertura-create'),
    path('cobertura-update/<int:pk>/',ListaTiposCoberturaUpdate.as_view(),name='cobertura-update'),
    path('zona/', ListaZonificacionListView.as_view(), name='zona'),
    path('zona-create/',ListaZonificacionCreate.as_view(),name='zona-create'),
    path('zona-update/<int:pk>/',ListaZonificacionUpdate.as_view(),name='zona-update'),
    path('tierra/', MovimientoTierraListView.as_view(), name='tierra'),
    path('tierra-create/',MovimientoTierraCreate.as_view(),name='tierra-create'),
    path('tierra-update/<int:pk>/',MovimientoTierraUpdate.as_view(),name='tierra-update'),
    path('consedi/', ListaTiposConsEdifListView.as_view(), name='consedi'),
    path('consedi-create/',ListaTiposConsEdifCreate.as_view(),name='consedi-create'),
    path('consedi-update/<int:pk>/',ListaTiposConsEdifUpdate.as_view(),name='consedi-update'),
    path('obraslineales/', ObrasLinealesListView.as_view(), name='obraslineales'),
    path('obraslineales-create/',ObrasLinealesCreate.as_view(),name='obraslineales-create'),
    path('obraslineales-update/<int:pk>/',ObrasLinealesUpdate.as_view(),name='obraslineales-update'),

],'catalogos')