# Generated by Django 3.0.3 on 2021-03-09 06:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cap2', '0013_auto_20210308_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearFicha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Nombre')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Descripción general del componente para esta fase')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('componente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Componente')),
                ('etapa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Etapa')),
                ('fase', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Fase')),
            ],
            options={
                'verbose_name': 'Ficha capítulo II',
                'verbose_name_plural': 'Fichas capítulo II',
                'ordering': ['-created'],
            },
        ),
    ]
