# Generated by Django 3.0.3 on 2021-03-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crearficha',
            name='title',
        ),
    ]
