# Generated by Django 3.0.3 on 2021-03-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap2', '0015_auto_20210328_1657'),
        ('ficha', '0003_imagenlocalizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crearficha',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='crearficha',
            name='content',
        ),
        migrations.AddField(
            model_name='crearficha',
            name='figura_loc',
            field=models.ImageField(default='null', upload_to='figuras_loc', verbose_name='Localización'),
        ),
        migrations.AddField(
            model_name='crearficha',
            name='modulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cap2.Modulo'),
        ),
        migrations.DeleteModel(
            name='ImagenLocalizacion',
        ),
    ]
